### ISSUE TITLE
Duplicated mapping key 'AlignTrailingComments' in default .clang-format style file

### ISSUE THREAD

**Issue by DreamAndDead** [Hazelight/vscode-unreal-angelscript-formatter#1]
First I use `Generate Config File` command in vscode and generate the .clang-format in working dir

Then I try to format as script using the style file and get error output below

```
$ clang-format Example.as
.clang-format:54:1: error: duplicated mapping key 'AlignTrailingComments'
AlignTrailingComments: true
^~~~~~~~~~~~~~~~~~~~~
Error reading .clang-format: Invalid argument
```

clang-format installed by msys2 pacman
```
$ clang-format --version
clang-format version 17.0.6
```

**Comment by DreamAndDead** [comment]
Suggest removing this line

https://github.com/Hazelight/vscode-unreal-angelscript-formatter/blob/b0d22243a2adfb65c5199235f4a56a59123ecacb/resources/default-style/.clang-format#L54

It's duplicated with

https://github.com/Hazelight/vscode-unreal-angelscript-formatter/blob/b0d22243a2adfb65c5199235f4a56a59123ecacb/resources/default-style/.clang-format#L48-L50

**Comment by nils-soderman** [comment]
`AlignTrailingComments: true` has now been removed from the default style config in [0.1.5](https://marketplace.visualstudio.com/items/Hazelight.unreal-angelscript-clang-format/changelog).

Thanks for reporting this issue!

Cheers,
Nils
